import type { Metadata } from "next";
import { createTheme, MantineProvider, ColorSchemeScript } from "@mantine/core";
import "./globals.css";
import "@mantine/core/styles.css";

const theme = createTheme({});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className="antialiased">
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
