import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { createTheme, MantineProvider, ColorSchemeScript } from "@mantine/core";
import "./globals.css";
import "@mantine/core/styles.css";
import Header from "@components/Header";

const theme = createTheme({});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className="antialiased flex flex-col h-dscreen">
        <MantineProvider theme={theme} forceColorScheme="dark">
          <Header />
          {children}
        </MantineProvider>
        <Analytics />
      </body>
    </html>
  );
}
